### ISSUE TITLE
How it works 

### ISSUE THREAD

**Issue by mhyssasilva** [sledgehamm3r/ESX-QBCore-Converter#2]
How to use it ? sorry I'm lost ahah

**Comment by Ventrex** [comment]
Same here, thought you had to open the program first
For Folder Path I filled in the path of my QBCore scripts
At the Replacement File i placed the qb-to-esx.txt file.
He SAY it is all done within 1 second, but nothing has been changed.

**Comment by Brutuss** [comment]
Same here. After processing nothing happens.
